Document: music-trainer
Title: Debian music-trainer Manual
Author: <insert document author here>
Abstract: This manual describes what music-trainer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/music-trainer/music-trainer.sgml.gz

Format: postscript
Files: /usr/share/doc/music-trainer/music-trainer.ps.gz

Format: text
Files: /usr/share/doc/music-trainer/music-trainer.text.gz

Format: HTML
Index: /usr/share/doc/music-trainer/html/index.html
Files: /usr/share/doc/music-trainer/html/*.html
